
target 'SwiftPodFirst_Example' do
  pod 'SwiftPodFirst', :path => '../'
  pod 'OCPodSecond', :path => '/Users/htsc/Desktop/MixedDemo/OCPodSecond'
  target 'SwiftPodFirst_Tests' do
    inherit! :search_paths
    
  end
end
